# Generated by Django 4.1.2 on 2022-11-03 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_link_analytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link_analytics',
            new_name='linkAnalytics',
        ),
    ]
